---
- hosts: all
  tasks:
    - name: Send authentication credentials to remote API
      uri:
        url: "http://auth.example.com/api/v1/login"
        method: POST
        body_format: json
        body:
          username: "admin"
          password: "supersecret"
          api_key: "abcdef123456"
        status_code: 200
        return_content: yes
      register: auth_response
